version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - unused
    - errorlint
    - staticcheck

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    disable:
      - shadow

issues:
  max-issues-per-linter: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
