// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.32.1
// source: sgard/v1/sgard.proto

package sgardpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GardenSync_Authenticate_FullMethodName = "/sgard.v1.GardenSync/Authenticate"
	GardenSync_PushManifest_FullMethodName = "/sgard.v1.GardenSync/PushManifest"
	GardenSync_PushBlobs_FullMethodName    = "/sgard.v1.GardenSync/PushBlobs"
	GardenSync_PullManifest_FullMethodName = "/sgard.v1.GardenSync/PullManifest"
	GardenSync_PullBlobs_FullMethodName    = "/sgard.v1.GardenSync/PullBlobs"
	GardenSync_Prune_FullMethodName        = "/sgard.v1.GardenSync/Prune"
)

// GardenSyncClient is the client API for GardenSync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GardenSync is the sgard remote sync service.
type GardenSyncClient interface {
	// Authenticate exchanges an SSH-signed challenge for a JWT token.
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
	// Push flow: send manifest, then stream missing blobs.
	PushManifest(ctx context.Context, in *PushManifestRequest, opts ...grpc.CallOption) (*PushManifestResponse, error)
	PushBlobs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PushBlobsRequest, PushBlobsResponse], error)
	// Pull flow: get manifest, then stream requested blobs.
	PullManifest(ctx context.Context, in *PullManifestRequest, opts ...grpc.CallOption) (*PullManifestResponse, error)
	PullBlobs(ctx context.Context, in *PullBlobsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PullBlobsResponse], error)
	// Prune removes orphaned blobs on the server.
	Prune(ctx context.Context, in *PruneRequest, opts ...grpc.CallOption) (*PruneResponse, error)
}

type gardenSyncClient struct {
	cc grpc.ClientConnInterface
}

func NewGardenSyncClient(cc grpc.ClientConnInterface) GardenSyncClient {
	return &gardenSyncClient{cc}
}

func (c *gardenSyncClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthenticateResponse)
	err := c.cc.Invoke(ctx, GardenSync_Authenticate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gardenSyncClient) PushManifest(ctx context.Context, in *PushManifestRequest, opts ...grpc.CallOption) (*PushManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushManifestResponse)
	err := c.cc.Invoke(ctx, GardenSync_PushManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gardenSyncClient) PushBlobs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PushBlobsRequest, PushBlobsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GardenSync_ServiceDesc.Streams[0], GardenSync_PushBlobs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PushBlobsRequest, PushBlobsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GardenSync_PushBlobsClient = grpc.ClientStreamingClient[PushBlobsRequest, PushBlobsResponse]

func (c *gardenSyncClient) PullManifest(ctx context.Context, in *PullManifestRequest, opts ...grpc.CallOption) (*PullManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullManifestResponse)
	err := c.cc.Invoke(ctx, GardenSync_PullManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gardenSyncClient) PullBlobs(ctx context.Context, in *PullBlobsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PullBlobsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GardenSync_ServiceDesc.Streams[1], GardenSync_PullBlobs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PullBlobsRequest, PullBlobsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GardenSync_PullBlobsClient = grpc.ServerStreamingClient[PullBlobsResponse]

func (c *gardenSyncClient) Prune(ctx context.Context, in *PruneRequest, opts ...grpc.CallOption) (*PruneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PruneResponse)
	err := c.cc.Invoke(ctx, GardenSync_Prune_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GardenSyncServer is the server API for GardenSync service.
// All implementations must embed UnimplementedGardenSyncServer
// for forward compatibility.
//
// GardenSync is the sgard remote sync service.
type GardenSyncServer interface {
	// Authenticate exchanges an SSH-signed challenge for a JWT token.
	Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error)
	// Push flow: send manifest, then stream missing blobs.
	PushManifest(context.Context, *PushManifestRequest) (*PushManifestResponse, error)
	PushBlobs(grpc.ClientStreamingServer[PushBlobsRequest, PushBlobsResponse]) error
	// Pull flow: get manifest, then stream requested blobs.
	PullManifest(context.Context, *PullManifestRequest) (*PullManifestResponse, error)
	PullBlobs(*PullBlobsRequest, grpc.ServerStreamingServer[PullBlobsResponse]) error
	// Prune removes orphaned blobs on the server.
	Prune(context.Context, *PruneRequest) (*PruneResponse, error)
	mustEmbedUnimplementedGardenSyncServer()
}

// UnimplementedGardenSyncServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGardenSyncServer struct{}

func (UnimplementedGardenSyncServer) Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedGardenSyncServer) PushManifest(context.Context, *PushManifestRequest) (*PushManifestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PushManifest not implemented")
}
func (UnimplementedGardenSyncServer) PushBlobs(grpc.ClientStreamingServer[PushBlobsRequest, PushBlobsResponse]) error {
	return status.Error(codes.Unimplemented, "method PushBlobs not implemented")
}
func (UnimplementedGardenSyncServer) PullManifest(context.Context, *PullManifestRequest) (*PullManifestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PullManifest not implemented")
}
func (UnimplementedGardenSyncServer) PullBlobs(*PullBlobsRequest, grpc.ServerStreamingServer[PullBlobsResponse]) error {
	return status.Error(codes.Unimplemented, "method PullBlobs not implemented")
}
func (UnimplementedGardenSyncServer) Prune(context.Context, *PruneRequest) (*PruneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Prune not implemented")
}
func (UnimplementedGardenSyncServer) mustEmbedUnimplementedGardenSyncServer() {}
func (UnimplementedGardenSyncServer) testEmbeddedByValue()                    {}

// UnsafeGardenSyncServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GardenSyncServer will
// result in compilation errors.
type UnsafeGardenSyncServer interface {
	mustEmbedUnimplementedGardenSyncServer()
}

func RegisterGardenSyncServer(s grpc.ServiceRegistrar, srv GardenSyncServer) {
	// If the following call panics, it indicates UnimplementedGardenSyncServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GardenSync_ServiceDesc, srv)
}

func _GardenSync_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GardenSyncServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GardenSync_Authenticate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GardenSyncServer).Authenticate(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GardenSync_PushManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GardenSyncServer).PushManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GardenSync_PushManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GardenSyncServer).PushManifest(ctx, req.(*PushManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GardenSync_PushBlobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GardenSyncServer).PushBlobs(&grpc.GenericServerStream[PushBlobsRequest, PushBlobsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GardenSync_PushBlobsServer = grpc.ClientStreamingServer[PushBlobsRequest, PushBlobsResponse]

func _GardenSync_PullManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GardenSyncServer).PullManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GardenSync_PullManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GardenSyncServer).PullManifest(ctx, req.(*PullManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GardenSync_PullBlobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullBlobsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GardenSyncServer).PullBlobs(m, &grpc.GenericServerStream[PullBlobsRequest, PullBlobsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GardenSync_PullBlobsServer = grpc.ServerStreamingServer[PullBlobsResponse]

func _GardenSync_Prune_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PruneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GardenSyncServer).Prune(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GardenSync_Prune_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GardenSyncServer).Prune(ctx, req.(*PruneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GardenSync_ServiceDesc is the grpc.ServiceDesc for GardenSync service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GardenSync_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sgard.v1.GardenSync",
	HandlerType: (*GardenSyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _GardenSync_Authenticate_Handler,
		},
		{
			MethodName: "PushManifest",
			Handler:    _GardenSync_PushManifest_Handler,
		},
		{
			MethodName: "PullManifest",
			Handler:    _GardenSync_PullManifest_Handler,
		},
		{
			MethodName: "Prune",
			Handler:    _GardenSync_Prune_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PushBlobs",
			Handler:       _GardenSync_PushBlobs_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "PullBlobs",
			Handler:       _GardenSync_PullBlobs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sgard/v1/sgard.proto",
}
